load_defaults: 9.0.0.beta1
development:
  adapter: solr
  url: <%= Settings.solr_url %>
test: &test
  adapter: solr
  url: <%= Settings.solr_url %>
staging:
  adapter: solr
  url: <%= Settings.solr_url %>
production:
  adapter: solr
  url: <%= Settings.solr_url %>
