default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: 5432
  password: <%= DockerSecrets.lookup(:database_password, ENV.fetch('DATABASE_PASSWORD', 'password')) %>
  pool: 100
  username: <%= DockerSecrets.lookup(:database_user, ENV.fetch('DATABASE_USER', 'postgres'))) %>

development:
  <<: *default
  database: digital_collections_development

test:
  <<: *default
  database: digital_collections_test

staging:
  <<: *default
  database: digital_collections_staging

production:
  <<: *default
  database: digital_collections_production
