pennlibs_web_version: '1.0.0-dev.0'
honeybadger:
  api_key: '12345'
redis:
  url: <%= ENV.fetch('REDIS_URL', 'redis://127.0.0.1:6379/0') %>
digital_catalog:
  url: find.library.upenn.edu
  path: /catalog
digital_repository:
  url: https://apotheca.library.upenn.edu
  webhook_token: '12345'
  api:
    resource:
      path: /v1/items
  sample_records:
    - 362ba96f-2fab-4a35-bd42-98f6667da1d0
    - 375a37c2-0cc4-4512-86f0-9113d9c80ca8
    - a0f6cbbf-ecfc-4e14-8fc7-d5cc47f9749c
    - e90ec77f-008c-43e9-b720-d73db60fe3a3
    - 4989943e-dcff-4048-902a-70aee6d3b97f
    - 9f489c21-0ecc-47ec-bc53-9f72080a2ca5
    - 4aec6af0-c57e-4f0d-b1f4-7945f4bf7212
    - f3c81151-8cd2-4664-ac39-d622dc7d7902
    - affe4574-a142-4430-b7c8-2d6da9e2e917
    - 51f5dcd4-d6d9-41a0-b59a-a183b56b74f5
    - 2cb93aa7-a2e9-41ef-95de-08ae48700a84
    - 070094ee-0f82-4b2f-b309-fb218734a91c
    - 7c0ccd8f-0e87-41f9-9303-0ae234d5def2
    - 0dcc59b1-a3c9-4a9b-9629-00480dfb2248
    - 352fcf1a-6fa3-4e2c-89ad-d52fec0d02fb
    - dc803994-827d-4d13-9a4f-c8a3a29a6013
    - d41b93c0-9012-42b2-bb17-85f1d828a045
    - 91495c7d-32bf-414e-ba2b-583349c532ec
    - df51650a-cbd7-41e1-83eb-0272acef6410
    - 4392de39-470f-4601-86ec-9abb388acd93
    - 433b2ee5-09ee-4894-939d-ca737c07b43a
    - a070e2d2-759d-4c03-a71a-8144176a42db
    - 6fd9c4c4-3cb9-465b-a90f-0d69625f05df
    - 93d2eb73-151e-44eb-9a65-a9d813a9db2d
    - 35fb98ee-c707-419f-bad9-422f68b75647
    - ef51af07-3a9d-4863-afc6-c84169adae80
    - d16cae7e-e31c-4c86-96a5-ca307190d39e
    - 53c931b0-f81b-4137-948d-d35c67b5d77d
collections:
  - name: Arnold and Deanne Kaplan Collection of Early American Judaica (University of Pennsylvania)
    representative_item: efa53ff7-86cb-4ba2-a536-a4a8ddac48b3
  - name: Alumni Association of the Philadelphia General Hospital School of Nursing Image Collection, Center for the Study of the History of Nursing, School of Nursing, University of Pennsylvania
    representative_item: 312853b9-38c7-4bd0-b34a-519decde65db
  - name: Collection of Indic Manuscripts
    representative_item: 957e45d5-e7b4-4a46-8387-e7c2a0335200
  - name: Edgar Fahs Smith Image Collection (University of Pennsylvania)
    representative_item: c56bf856-785d-4251-92e5-597c2ca3d3ff
  - name: Furness Theatrical Image Collection (University of Pennsylvania)
    representative_item: d4d238bf-e7ec-4624-af02-8233c437fe8b
  - name: Issac Leeser Collection at the Herbert D. Katz Center for Advanced Judaic Studies (University of Pennsylvania)
    representative_item: 1dadcc2a-7765-4a42-9bad-c87c2a6ee6fe
  - name: Jatindra Mohan Bhattacharjee Collection
    representative_item: 5902d878-186f-4121-996b-04a78feaf3c1
  - name: Keffer Collection of Sheet Music (University of Pennsylvania)
    representative_item: 9804336a-2591-4087-8de8-b7f0f6838566
  - name: Laurence and Ayşe Gürsan-Salzmann Collection
    representative_item: 5e0d2cdb-165e-4f0c-8afa-126d772b7091
  - name: Lenkin Family Collection of Photography (University of Pennsylvania)
    representative_item: 8d1ba9ec-4ee6-43d3-a535-c9e7abb394ae
  - name: 'Mahler-Werfel Papers: Photographs, 1888-1984 (University of Pennsylvania)'
    representative_item: 4ce1458f-e922-4736-ac8a-aeda23896211
  - name: Marian Anderson Collection of Photographs, 1898-1992 (University of Pennsylvania)
    representative_item: 7b214b28-f748-4c82-9b32-821651616b94
  - name: Marian Anderson Papers (University of Pennsylvania)
    representative_item: 988c1f30-23a7-4b12-ab52-2da7ea65aedb
  - name: Mary Binney Wheeler Image Collection
    representative_item: f436c52e-f41e-40d7-b33d-e269abe76e91
  - name: Penn in the Age of Franklin (University of Pennsylvania)
    representative_item: dda4356e-d480-46ae-8405-f701da377f73
  - name: Photographs from the American Poetry Review Records, 1971-1998 (University of Pennsylvania)
    representative_item: d9c7d38a-d300-4457-a349-eb238bd64901
  - name: Sabato Morais Collection (University of Pennsylvania)
    representative_item: 86ef8378-88e9-4352-b619-a5b4ae6c15ff
  - name: Theodore Dreiser Papers (University of Pennsylvania)
    representative_item: 8cab981d-e9d8-4aa5-936e-f7297add0256
  - name: University Archives Image Collection (University of Pennsylvania)
    representative_item: 47bc78cd-d905-41c9-b0fc-7d4a694ffd51
