name: digital_collections

services:
  chrome:
    image: ghcr.io/browserless/chromium:v2.27.0
    ports:
      - "3333:3333"
    volumes:
      - .:/app:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  solrcloud:
    image: solr:9.8.1
    ports:
      - "8984:8983"
    volumes:
      - solrcloud_data:/var/solr
      - ./solr/conf:/opt/solr/configsets/dcoll
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
      - "-Dsolr.modules=analysis-extras"

volumes:
  db_data:
  solrcloud_data:
