# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.2'

gem 'blacklight', github: 'projectblacklight/blacklight', branch: 'main'
gem 'blacklight_range_limit'
gem 'bootsnap', require: false
gem 'config'
gem 'devise'
gem 'devise-guests', '~> 0.8'
gem 'faraday'
gem 'honeybadger'
gem 'importmap-rails'
gem 'pg', '~> 1.1'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.0.2'
gem 'rsolr'
gem 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'upennlib-rubocop', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 7.0.0'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
  gem 'rspec-sidekiq'
end

group :development do
  gem 'web-console'
end
