# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.2'

gem 'bootsnap', require: false
gem 'config'
gem 'importmap-rails'
gem 'pg', '~> 1.1'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.0.2'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'upennlib-rubocop'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 7.0.0'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
end

group :development do
  gem 'web-console' # Use console on exceptions pages [https://github.com/rails/web-console]
end
