solr:
  url: <%= ENV.fetch('SOLR_URL', 'http://127.0.0.1:8983/solr/digital-collections-development') %>
redis:
  username: ''
  password: ''
digital_repository:
  url: https://apotheca-staging.library.upenn.edu
  sample_records:
    - 31452392-45e9-4ee5-a7f6-d7d8e71b1362
    - 2b4caccf-bf44-418b-b172-a20a9daeaed5
    - 1ead9f44-605b-4ef8-ae30-c68e7ff2c737
    - 0032b909-b5ad-4aba-8a84-76253fe848c2
