honeybadger:
  api_key: <%= DockerSecrets.lookup(:honeybadger_api_key) %>
solr:
  url: <%= DockerSecrets.lookup(:solr_url, ENV.fetch('SOLR_URL', 'http://127.0.0.1:8983/solr/digital-collections')) %>
redis:
  password: <%= DockerSecrets.lookup(:redis_password, ENV.fetch('REDIS_PASSWORD', '')) %>
  username: <%= DockerSecrets.lookup(:redis_username, ENV.fetch('REDIS_USERNAME', '')) %>
