honeybadger:
  api_key: <%= DockerSecrets.lookup(:honeybadger_api_key) %>
solr:
  url: <%= DockerSecrets.lookup(:solr_url, ENV.fetch('SOLR_URL', 'http://127.0.0.1:8983/solr/digital-collections')) %>
redis:
  username: <%= DockerSecrets.lookup(:redis_username, ENV.fetch('REDIS_USERNAME', '')) %>
  password: <%= DockerSecrets.lookup(:redis_password, ENV.fetch('REDIS_PASSWORD', '')) %>
ms_clarity:
  id: wft82535jm
google_analytics:
  tag_id: GTM-N79KMH6F
digital_repository:
  host: digitalrepository.library.upenn.edu
  webhook_token: <%= DockerSecrets.lookup(:digital_repository_token, 'sample_token') %>
  api:
    resource:
      items:
        path: /v1/items
    iiif:
      items:
        path: /iiif/items
  sample_records: