version: "3"

# Project-specific variables
vars:
  PROJECT_NAME: digital-collections
  PROJECT_PATH: /{{.PROJECT_NAME}}
  PROJECT_DOMAIN: digitalcollections-dev
  PROJECT_FQDN_INT: "{{.PROJECT_DOMAIN}}.library.upenn.int"
  PROJECT_FQDN_EXT: "{{.PROJECT_DOMAIN}}.library.upenn.edu"
  PROJECT_CONTAINER_NAME: ""
  PROJECT_PORT_EXT: 80
  PROJECT_PORT_INT: 80
  PROJECT_PORT_TLS_EXT: 443
  PROJECT_PORT_TLS_INT: 443

  # Ansible specific config
  ANSIBLE_CONFIG: "{{.PROJECT_PATH}}/ansible/ansible.cfg"
  ANSIBLE_CONTAINER_NAME: "{{.PROJECT_NAME}}"
  ANSIBLE_CONTAINER_IP: 172.20.128.2
  ANSIBLE_DOCKER_IMAGE: "{{.ANSIBLE_CONTAINER_NAME}}:latest"
  ANSIBLE_INVENTORY: "{{.PROJECT_PATH}}/ansible/inventories/development"
  ANSIBLE_NETWORK_NAME: '{{.PROJECT_NAME | replace "-" "_"}}'
  ANSIBLE_NETWORK_SUBNET: 172.20.128.0/24
  ANSIBLE_REQUIREMENTS: "{{.PROJECT_PATH}}/ansible/roles/requirements.yml"
  ANSIBLE_SITE_YML: "{{.PROJECT_PATH}}/ansible/site.yml"

  CONTAINER_NAME: '{{.CONTAINER_NAME | default .ANSIBLE_CONTAINER_NAME}}'

  UID:
    sh: id -u
  GID:
    sh: id -g

  # Docker
  DOCKER_CONTEXT: "{{.PROJECT_NAME}}"
  DOCKER_TLS_PORT_INT: 2376
  DOCKER_TLS_PORT_EXT: 3486
  DOCKER_REGISTRY_MIRROR: registry-mirror.library.upenn.int:172.16.225.202
  
  HOSTS_ENTRY: "{{.ANSIBLE_CONTAINER_IP}} {{.PROJECT_FQDN_EXT}} {{.PROJECT_FQDN_INT}} {{.PROJECT_DOMAIN}}"
  HOSTS_FILE: "/etc/hosts"

  VAULT_ADDR: https://vault.library.upenn.edu

tasks:
  # === General Tasks ===
  default:
    desc: Show available tasks
    cmd: task --list

  up:
    desc: Start the development environment
    cmds:
      - task: context:use_default
      - task: network:create
      - task: container:build
      - task: ansible_container:run
      - task: ansible:run
      - task: hosts:create
      - task: context:create
      - task: print-success

  down:
    desc: Stop and remove the development environment
    cmds:
      - task: context:use_default
      - task: container:stop
      - task: container:remove
      - task: network:remove
      - task: hosts:remove
      - task: context:remove
    silent: false

  reload:
    desc: Reload the development environment
    cmds:
      - task: down
      - task: up

  provision:
    desc: Run ansible playbook without recreating container
    cmds:
      - task: ansible:run

  status:
    desc: Show status of the development environment
    cmds:
      - echo "=== Container Status ==="
      - docker ps -a --filter name={{.ANSIBLE_CONTAINER_NAME}}
      - echo "=== Network Status ==="
      - docker network inspect {{.ANSIBLE_NETWORK_NAME}} 2>/dev/null || echo "Network not found"

  test:
    desc: Run tests inside the container
    dir: "{{.PROJECT_PATH}}/rails_app"
    deps:
      - context:create
      - context:use
    cmds:
      - task: container:exec
        vars:
          EXEC_CMD: "bundle exec rspec"
          EXEC_CONTAINER: ""

  console:
    desc: Open Rails console
    dir: "{{.PROJECT_PATH}}/rails_app"
    cmds:
      - task: container:exec
        vars:
          EXEC_CMD: "bundle exec rails c"
          EXEC_CONTAINER: ""

  help:
    desc: Show help and common commands
    cmds:
      - task: print-help

  # === Ansible Tasks ===
  ansible:run:
    desc: Run Ansible playbook
    deps:
      - ansible:install
    vars:
      ANSIBLE_VERBOSITY: '{{.ANSIBLE_VERBOSITY | default "-vvv"}}'
    env:
      ANSIBLE_CONFIG: "{{.ANSIBLE_CONFIG}}"
      ANSIBLE_FORCE_COLOR: true
      PYTHONUNBUFFERED: 1
    cmds: 
      - echo "Running Ansible playbook"
      - task: container:exec
        vars:
          EXEC_CMD: ansible-playbook -i {{.ANSIBLE_INVENTORY}} -e "ansible_hashi_vault_token=${VAULT_TOKEN} ansible_hashi_vault_addr={{.VAULT_ADDR}} " --limit all --tags all {{.ANSIBLE_VERBOSITY}} {{.ANSIBLE_SITE_YML}}

  ansible:install:
    desc: Install galaxy collections and roles
    vars:
      ANSIBLE_VERBOSITY: '{{.ANSIBLE_VERBOSITY | default "-vvv"}}'
    env:
      ANSIBLE_CONFIG: "{{.ANSIBLE_CONFIG}}"
      ANSIBLE_FORCE_COLOR: true
      PYTHONUNBUFFERED: 1
    cmds:
      - echo "Installing Galaxy Collections and Roles"
      - task: container:exec
        vars:
          EXEC_CMD: "ansible-galaxy install -f -r {{.ANSIBLE_REQUIREMENTS}}"

  ansible_container:run:
    desc: Run ansible controller container
    status:
      - docker ps | grep -q {{.CONTAINER_NAME}}
    env:
      VAULT_TOKEN:
        sh: |
          if [ -n "$VAULT_TOKEN" ]; then
            echo "$VAULT_TOKEN"
          else
            echo "Please enter your LDAP credentials:" >&2
            read -p "Username: " LDAP_USERNAME >&2
            read -sp "Password: " LDAP_PASSWORD >&2
            echo "" >&2
            
            RESPONSE=$(curl -s --request POST \
              --data "{\"password\": \"$LDAP_PASSWORD\"}" \
              ${VAULT_ADDR}/v1/auth/ldap/login/$LDAP_USERNAME)
            
            TOKEN=$(echo $RESPONSE | grep -o '"client_token":"[^"]*' | cut -d'"' -f4)
            
            if [ -z "$TOKEN" ]; then
              echo "Failed to obtain Vault token. Please check your credentials." >&2
              exit 1
            fi
            
            echo "Successfully obtained Vault token" >&2
            echo "$TOKEN"
          fi
    cmds:
      - 'echo Starting container: "{{.CONTAINER_NAME}}"'
      - |
        docker run -d \
        --name {{.CONTAINER_NAME}} \
        --hostname {{.CONTAINER_NAME}} \
        --network {{.ANSIBLE_NETWORK_NAME}} \
        --ip {{.ANSIBLE_CONTAINER_IP}} \
        --add-host="{{.DOCKER_REGISTRY_MIRROR}}" \
        --security-opt seccomp=unconfined \
        --security-opt apparmor=unconfined \
        --cap-add=SYS_ADMIN \
        --privileged \
        -e "VAULT_TOKEN={{.VAULT_TOKEN}}" \
        -e "VAULT_ADDR={{.VAULT_ADDR}}" \
        -e "GID={{.GID}}" \
        -e "UID={{.UID}}" \
        -p {{.PROJECT_PORT_EXT}}:{{.PROJECT_PORT_INT}} \
        -p {{.PROJECT_PORT_TLS_EXT}}:{{.PROJECT_PORT_TLS_INT}} \
        -v "$(dirname $(pwd)):{{.PROJECT_PATH}}" \
        {{.ANSIBLE_DOCKER_IMAGE}}

  # === Docker Context Tasks ===
  context:create:
    desc: Create Docker context for remote Docker access
    deps:
      - context:remove_certs
      - context:copy_certs
    status:
      - docker context inspect {{.ANSIBLE_CONTAINER_NAME}} >/dev/null 2>&1
    cmds: 
      - 'echo Creating Docker context: "{{.ANSIBLE_CONTAINER_NAME}}"'
      - docker context create {{.ANSIBLE_CONTAINER_NAME}} --description "{{.PROJECT_NAME}} development Docker context"
        --docker "host=tcp://{{.ANSIBLE_CONTAINER_IP}}:{{.DOCKER_TLS_PORT_INT}},ca=.swarm_certificates/ca.pem,cert=.swarm_certificates/cert.pem,key=.swarm_certificates/key.pem"

  context:remove:
    desc: Delete Docker context
    cmds:
      - 'echo "Deleting Docker context: {{.ANSIBLE_CONTAINER_NAME}}"'
      - docker context rm {{.ANSIBLE_CONTAINER_NAME}} -f || true

  context:use:
    desc: Switch to the development Docker context
    cmds: 
      - 'echo "Switching to Docker context: {{.ANSIBLE_CONTAINER_NAME}}"'
      - docker context use {{.ANSIBLE_CONTAINER_NAME}}
      
  context:use_default:
    desc: Switch to the default Docker context
    cmds:
      - 'echo "Switching to default Docker context: default"'
      - docker context use default
      
  context:copy_certs:
    desc: Copy certificates from container to host
    status:
      - test -f .swarm_certificates/ca.pem
      - test -f .swarm_certificates/cert.pem
      - test -f .swarm_certificates/key.pem
    cmd: |
      echo "Creating certificates directory"
      mkdir -p .swarm_certificates

      echo "Copying certificates from container"
      docker cp {{.ANSIBLE_CONTAINER_NAME}}:/certs/client/. .swarm_certificates/

      echo "Setting permissions on the container certificates"
      chmod 600 .swarm_certificates/key.pem
      chmod 644 .swarm_certificates/cert.pem
      chmod 644 .swarm_certificates/ca.pem

      echo "Certificates copied to .swarm_certificates/"

  context:remove_certs:
    desc: Remove TLS certificates
    status:
      - test -f .swarm_certificates/ca.pem
      - test -f .swarm_certificates/cert.pem
      - test -f .swarm_certificates/key.pem
    cmds: 
      - echo "Removing certificates"
      - rm -fr .swarm_certificates/*.pem .swarm_certificates/*.cnf

  # === Docker Container Tasks ===
  container:build:
    desc: Build the Docker image
    cmds:
      - echo "Building Docker image"
      - docker build -t {{.ANSIBLE_DOCKER_IMAGE}} .

  container:exec:
    desc: Run a command within the controller container
    deps:
      - container:wait_until_running
    cmds:
      - echo Running '{{.EXEC_CMD}}' inside controller container
      - docker exec -t -u "{{.UID}}:{{.GID}}" {{.CONTAINER_NAME}} /bin/sh -c '{{.EXEC_CMD}}'
    vars:
      EXEC_CMD: '{{.EXEC_CMD | default "ps aux"}}'

  container:exists:
    desc: Determine if the container exists
    cmd: docker ps | grep -q {{.CONTAINER_NAME}}

  container:wait_until_running:
    desc: Determine if the container is running
    cmd: |
      until docker ps --filter "name={{.CONTAINER_NAME}}" --filter "status=running" | grep -q "{{.CONTAINER_NAME}}"; do \
        sleep 1; \
      done

  container:logs:
    desc: Show container logs
    deps:
      - container:wait_until_running
    cmd: docker logs -f {{.CONTAINER_NAME}}

  container:remove:
    desc: Remove the container if it exists
    cmd: docker rm -f {{.CONTAINER_NAME}} || true

  container:start:
    desc: Start the container
    cmd: docker start {{.CONTAINER_NAME}}

  container:stop:
    desc: Stop the container if it's running
    cmd: docker stop {{.CONTAINER_NAME}} || true

  # === Hosts Tasks ===
  hosts:create:
    desc: Add entry to /etc/hosts file entry
    status:
      - grep -q "{{.HOSTS_ENTRY}}" /etc/hosts
    cmds:
      - echo "Adding {{.HOSTS_ENTRY}} to /etc/hosts file"
      - task: hosts:remove
      - echo {{.HOSTS_ENTRY}} | sudo tee -a /etc/hosts >/dev/null

  hosts:remove:
    desc: Delete entries from /etc/hosts file
    cmds:
      - |
          sudo sed -i.bak '/{{.HOSTS_ENTRY}}/d' {{.HOSTS_FILE}}
          sudo rm -f {{.HOSTS_FILE}}.bak
  # === Docker Network Tasks ===
  network:create:
    desc: Create Docker network if it doesn't exist
    status:
      - docker network inspect {{.ANSIBLE_NETWORK_NAME}} >/dev/null 2>&1
    cmds:
      - 'echo "Creating Docker network: {{.ANSIBLE_NETWORK_NAME}}"'
      - docker network create --driver bridge --subnet={{.ANSIBLE_NETWORK_SUBNET}} {{.ANSIBLE_NETWORK_NAME}}

  network:remove:
    desc: Remove Docker network if no containers are using it
    cmd: |
      if docker network inspect {{.ANSIBLE_NETWORK_NAME}} >/dev/null 2>&1; then
        CONTAINERS_IN_NETWORK=$(docker network inspect {{.ANSIBLE_NETWORK_NAME}} -f '{{`{{len .Containers}}`}}')
        if [ "$CONTAINERS_IN_NETWORK" -eq 0 ]; then
          echo "Removing Docker network: {{.ANSIBLE_NETWORK_NAME}}"
          docker network rm {{.ANSIBLE_NETWORK_NAME}} >/dev/null 2>&1
        else
          echo "Network {{.ANSIBLE_NETWORK_NAME}} still has $CONTAINERS_IN_NETWORK container(s) attached, skipping removal"
        fi
      else
        echo "Network {{.ANSIBLE_NETWORK_NAME}} not found"
      fi

  # === Internal Tasks
  print-success:
    internal: true
    cmd: |
      echo "Setup complete!"
      echo "Container '{{.CONTAINER_NAME}}' is running"
      echo "Access the application at: http://{{.PROJECT_FQDN_EXT}}:{{.PROJECT_PORT_EXT}}"
      echo ""
      echo "To view container logs, run: task logs"

  print-help:
    internal: true
    cmd: |
      echo "{{.PROJECT_NAME}} Development Environment - Task Commands"
      echo "=========================================================="
      echo ""
      echo "Common commands:"
      echo "  task up         - Start the development environment"
      echo "  task down       - Stop and remove the development environment"
      echo "  task reload     - Restart the development environment"
      echo "  task provision  - Run Ansible playbook without recreating container (verbose)"
      echo "  task provision:quiet - Run Ansible playbook without recreating container (quiet)"
      echo "  task logs       - Show container logs"
      echo "  task status     - Show environment status"
      echo "  task console    - Open Rails console"
      echo "  task test       - Run tests"
      echo "  task clean      - Remove everything including Docker image"
      echo ""
      echo "Docker Context Commands:"
      echo "  task context:create - Create Docker context for remote access"
      echo "  task context:use    - Switch to the development Docker context"
      echo "  task context:remove - Delete the Docker context"
      echo "  task context:copy_certs - Copy certificates from container"
      echo ""
      echo "For a complete list of tasks, run: task --list"ß