version: "3"

includes:
  app:
    taskfile: https://gitlab.library.upenn.edu/devops/taskfile/-/raw/main/Taskfile.yml
    vars:
      PROJECT_NAME: "digital-collections"
      PROJECT_DOMAIN: digitalcollections-dev
      ANSIBLE_NETWORK_SUBNET: 172.16.5.0/24
      ANSIBLE_CONTAINER_IP: "172.16.5.10"
      ANSIBLE_CONTAINER_NAME: "digital-collections"
