version: "3"

# Project-specific variables
vars:
  PROJECT_NAME: digital-collections
  PROJECT_DOMAIN: digitalcollections-dev
  PROJECT_CONTAINER_NAME: ""

  # Docker
  DOCKER_TLS_PORT_INT: 2376
  DOCKER_TLS_PORT_EXT: 3486

includes:
  remote:
    taskfile: https://gitlab.library.upenn.edu/devops/taskfile/-/raw/main/Taskfile.yml
    dir: .
