# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'etc'

def get_current_user_info(default_uid = 1000, default_gid = 1000)
  begin
    user = Etc.getpwuid
    { uid: user.uid, gid: user.gid }
  rescue StandardError
    { uid: default_uid, gid: default_gid }
  end
end

class Token
  def to_s
    begin
      Vault.address = "https://vault.library.upenn.edu"
      vault_instance = Vault.auth.token(ENV.fetch('VAULT_TOKEN', ''))
      token = ENV.fetch('VAULT_TOKEN')

    rescue
      begin
        puts "\nInvalid local Vault token, or local Vault token does not exist. Please enter Vault credentials."

        print "HashiCorp Vault username: "
        hv_user = STDIN.gets.chomp
        print "HashiCorp Vault password: "
        hv_pass = STDIN.noecho(&:gets).chomp

        Vault.address = "https://vault.library.upenn.edu"
        vault_instance = Vault.auth.ldap(hv_user, hv_pass)
        vault_instance.auth.client_token
      rescue
        puts "Invalid Vault credentials, try again."
        retry
      end
    end
  end
end

VAGRANT_NODES = {
  "digital-collections" => { ip: "172.20.128.2" }
}

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-hostsupdater", "vault"]
  config.ssh.insert_key = false

  $script = <<-SCRIPT
    docker exec digital-collections /bin/sh -c "
    export ANSIBLE_CONFIG=/digital-collections/ansible/ansible.cfg
    ansible-galaxy install -r /digital-collections/ansible/roles/requirements.yml
    ansible-playbook \
      -i /digital-collections/ansible/inventories/development \
      --extra-vars 'ansible_hashi_vault_token=#{Token.new}' \
      --limit all \
      --tags all \
      -vvv \
      /digital-collections/ansible/site.yml"
  SCRIPT

  config.trigger.after :up do |trigger|
    trigger.name = "Run ansible playbook"
    trigger.info = "Container is ready, running the playbook!"
    trigger.run = {inline: $script}
  end

  VAGRANT_NODES.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.hostname = hostname
      cfg.vm.network :private_network, ip: info[:ip]

      config.vm.provider "docker" do |d|
        d.create_args = [
          "--add-host=registry-mirror.library.upenn.int=172.16.225.202",
          "--security-opt", "seccomp=unconfined",
          "--security-opt", "apparmor=unconfined",
          "--cap-add=SYS_ADMIN"
        ]
        d.env = {
          "GID" => get_current_user_info[:gid],
          "UID" => get_current_user_info[:uid]
        }
        #d.image = "gitlab.library.upenn.edu/devops/docker-images/development/almalinux:main"
        d.build_dir = "."
        d.name = "digital-collections"
        d.pull = false
        d.ports = ["2222:22", "3486:2375", "8080:80"]
        d.privileged = true
        d.remains_running = true
      end

      if hostname == "digital-collections"
        cfg.vm.synced_folder "../", "/digital-collections"
      end
    end
  end

  config.hostsupdater.aliases = {
    "172.20.128.2" => [
      "digitalcollections-dev.library.upenn.edu",
      "digitalcollections-dev.library.upenn.int"
    ]
  }
end
